### PR TITLE
[WIP] Update covid19israel.source-spec.yaml: remove irrelevant dependencies, change ordering

### PR DESCRIPTION
**Pull request by kalkairis**
**Work In Progress**

removing irrelevant dependency.

### CODE REVIEW

**Comment by OriHoch** [comment]
this causes more pipelines to run in parallel, is there a reason you want to do that?

**Comment by kalkairis** [comment]
I assumed that it is good practice. The thing is that this code is not dependant on other codes but the idf_ neighborhoods keeps failing (our fault) and I want this code to continue running regardless.

**Comment by OriHoch** [comment]
given the RAM problems, I suggest to run less things in parallel

if you want to ignore an error for a pipeline step, wrap it in a try catch

**Comment by kalkairis** [comment]
I'll move things around

**Comment by OriHoch** [comment]
given the instability of the pipelines, maybe it's best to write a success / failure file at the end of each step,
then add a final pipeline step which depends on all other steps and checks success/failure files and raises an exception if any step failed - to get a visual feedback in the pipelines dashboard if there were any failures

**Comment by kalkairis** [comment]
I'll figure something out and then fix this PR

**Comment by kalkairis** [comment]
This hopefully should work. I am leaving some things to run simultaneously since they should not take up too much RAM resources.
Also I moved the code that keeps on failing to the end. Apparently (according to other team members) none of the other sections is dependent upon it so this would make work better.

Thanks!

**Comment by kalkairis** [comment]
I just noticed that everything seems to run OK.
I say don't merge this PR for the time being. 
Sorry for all the trouble

**Pull request closed without merging**
